export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const ADD_USER_DETAILS_START = "ADD_USER_DETAILS_START";
export const ADD_USER_DETAILS_SUCCESS = "ADD_USER_DETAILS_SUCCESS";
export const ADD_USER_DETAILS_FAILURE = "ADD_USER_DETAILS_FAILURE";

export const GET_USER_DETAILS_START = "GET_USER_DETAILS_START";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";

export const ADD_RESUME_START = "ADD_RESUME_START";
export const ADD_RESUME_SUCCESS = "ADD_RESUME_SUCCESS";
export const ADD_RESUME_FAILURE = "ADD_RESUME_FAILURE";

export const ADD_PROJECT_START = "ADD_PROJECT_START";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAILURE = "ADD_PROJECT_FAILURE";

export const GET_PROJECTS_START = "GET_PROJECTS_START";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";

export const UPDATE_PROJECT_START = "UPDATE_PROJECT_START";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";

export const DELETE_PROJECT_START = "DELETE_PROJECT_START";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

export const ADD_SKILL_START = "ADD_SKILL_START";
export const ADD_SKILL_SUCCESS = "ADD_SKILL_SUCCESS";
export const ADD_SKILL_FAILURE = "ADD_SKILL_FAILURE";

export const GET_SKILL_SUCCESS = "GET_SKILL_SUCCESS";
export const GET_SKILL_FAILURE = "GET_SKILL_FAILURE";

export const UPDATE_SKILL_START = "UPDATE_SKILL_START";
export const UPDATE_SKILL_SUCCESS = "UPDATE_SKILL_SUCCESS";
export const UPDATE_SKILL_FAILURE = "UPDATE_SKILL_FAILURE";

export const DELETE_SKILL_START = "DELETE_SKILL_START";
export const DELETE_SKILL_SUCCESS = "DELETE_SKILL_SUCCESS";
export const DELETE_SKILL_FAILURE = "DELETE_SKILL_FAILURE";

export const ADD_EXPERIENCE_START = "ADD_EXPERIENCE_START";
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const ADD_EXPERIENCE_FAILURE = "ADD_EXPERIENCE_FAILURE";

export const GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS";
export const GET_EXPERIENCE_FAILURE = "GET_EXPERIENCE_FAILURE";

export const UPDATE_EXPERIENCE_START = "UPDATE_EXPERIENCE_START";
export const UPDATE_EXPERIENCE_SUCCESS = "UPDATE_EXPERIENCE_SUCCESS";
export const UPDATE_EXPERIENCE_FAILURE = "UPDATE_EXPERIENCE_FAILURE";

export const DELETE_EXPERIENCE_START = "DELETE_EXPERIENCE_START";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_FAILURE = "DELETE_EXPERIENCE_FAILURE";
